name: test

on: pull_request

env:
  FOUNDRY_PROFILE: ci
  CONFIGS: | 
    certora/confs/setup/sanity_CommonAdminOwner.conf
    certora/confs/setup/sanity_YieldExposedTokenMock.conf

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: bun install
        run: |
          echo $PATH
          bun install
          forge soldeer install

      - name: run configs
        uses: Certora/certora-run-action@v1
        with:
          use-beta: true
          configurations: ${{ env.CONFIGS }}
          solc-versions: 0.8.28
          solc-remove-version-prefix: "0."
          job-name: "Verified Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
