name: test

on: pull_request

env:
  FOUNDRY_PROFILE: ci
  CONFIGS: | 
    certora/confs/setup/sanity_CustomTokenMock.conf
    certora/confs/setup/sanity_GenericCustomToken.conf
    certora/confs/setup/sanity_GenericNativeConverter.conf
    certora/confs/setup/sanity_GenericVbToken.conf
    certora/confs/setup/sanity_MockVault.conf
    certora/confs/setup/sanity_NativeConverterMock.conf
    certora/confs/setup/sanity_TransferFeeUtilsVbUSDT.conf
    certora/confs/setup/sanity_VaultBridgeTokenInitializer.conf
    certora/confs/setup/sanity_VaultBridgeTokenMock.conf
    certora/confs/setup/sanity_VbETH.conf
    certora/confs/setup/sanity_WETH.conf
    certora/confs/GenericNativeConverter-other.conf
    certora/confs/GenericNativeConverter-VbETH.conf
    certora/confs/GenericNativeConverter-VbUSDT.conf
    certora/confs/WETHNativeConverter-other.conf
    certora/confs/WETHNativeConverter-VbETH.conf
    certora/confs/WETHNativeConverter-VbUSDT.conf

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: bun install
        run: |
          forge soldeer install
          bun install || true

      - name: run configs
        uses: Certora/certora-run-action@v1
        with:
          use-alpha: true
          configurations: ${{ env.CONFIGS }}
          solc-versions: 0.8.28
          solc-remove-version-prefix: "0."
          job-name: "Verified Rules"
          certora-key: ${{ secrets.CERTORAKEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
